# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3374f942409f067482a9638194e1020d9060f224fa262c058fd7eea78c9fcc191ed63e7952f7a9ee3797eb3d199d43e553ee346c34de26932fb415a8a0edb7af

test:
  secret_key_base: 53d43d68690f09eb415dd0091471512809cdde048235effd34ef4c32bd4069d03d1b63f0398301ab8e2030a3413340c6a666ba177c7575e89b2643f75b2d2e22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
